name: 'Headless Graphql Compose'
description: 'configures drupal for Consumer Mesh'
type: 'Content type'

recipes:
  - core/recipes/image_media_type
  - core/recipes/document_media_type
  - core/recipes/tags_taxonomy
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  - core/recipes/core_recommended_maintenance

install:
  - admin_toolbar
  - admin_toolbar_tools
  - admin_toolbar_search
  - ckeditor_media_embed
  - coffee
  - config
  - field_ui
  - gin
  - gin_login
  - gin_toolbar
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_fragments
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_metatags
  - graphql_compose_preview
  - graphql_compose_routes
  - graphql_compose_users
  - graphql_compose_views
  - help
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - views_ui
  - view_unpublished
  - webform
  - webform_rest
  - weight

config:
  import:
    admin_toolbar: '*'
    admin_toolbar_tools: '*'
    admin_toolbar_search: '*'
    ckeditor_media_embed: '*'
    gin: '*'
    gin_login: '*'
    coffee: '*'
  actions:
    system.site:
      simple_config_update:
        page.front: /home
    block.block.gin_admin:
      simple_config_update:
        status: false
    block.block.gin_branding:
      simple_config_update:
        status: false
    block.block.gin_local_actions:
      simple_config_update:
        region: content
        weight: -10
    block.block.gin_local_tasks:
      simple_config_update:
        status: false
    block.block.gin_page_title:
      simple_config_update:
        region: header
        weight: -10
    block.block.gin_primary_local_tasks:
      simple_config_update:
        region: header
        weight: -5
        settings.secondary: true
    block.block.gin_tools:
      simple_config_update:
        status: false
    block.block.gin_content:
      simple_config_update:
        status: content
        weight: -5
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'gin'
    ckeditor_media_embed.settings
      simpleConfigUpdate:
        embed_provider: '//noembed.com/embed?url={url}&callback={callback}'
