name: 'Headless Graphql Compose'
description: 'configures drupal for Consumer Mesh'
type: 'Content type'

recipes:
  - core/recipes/image_media_type
  - core/recipes/tags_taxonomy
  - core/recipes/basic_html_format_editor
  - core/recipes/full_html_format_editor
  - core/recipes/restricted_html_format
  - core/recipes/administrator_role
  - core/recipes/content_editor_role
  - core/recipes/core_recommended_maintenance

install:
  - admin_toolbar
  - coffee
  - config
  - dropzonejs
  - gin
  - gin_login
  - gin_toolbar
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_routes
  - graphql_compose_users
  - graphql_compose_views
  - graphql_compose_metatags
  - graphql_compose_preview
  - graphql_compose_fragments
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - webform
  - webform_rest
  - weight

config:
  import:

  actions:
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'gin'
