name: 'Headless Graphql Compose'
description: 'configures drupal for Consumer Mesh'
type: 'Content type'

recipes:
  - core/recipes/image_media_type
  - core/recipes/core_recommended_admin_theme
  - core/recipes/tags_taxonomy

install:
  - admin_toolbar
  - graphql_compose
  - metatag
  - webform
  - webform_rest
  - weight

config:
  import:
    
  actions:
