name: 'Headless Graphql Compose'
description: 'configures drupal for Consumer Mesh'
type: 'Content type'

recipes:
  - core/recipes/administrator_role
  - core/recipes/basic_html_format_editor
  - core/recipes/content_editor_role
  - core/recipes/core_recommended_maintenance
  - core/recipes/document_media_type
  - core/recipes/full_html_format_editor
  - core/recipes/image_media_type
  - core/recipes/restricted_html_format
  - core/recipes/tags_taxonomy
  - core/recipes/standard_responsive_images

install:
  - ckeditor_media_embed
  - coffee
  - config
  - field_ui
  - gin
  - gin_login
  - graphql_compose
  - graphql_compose_edges
  - graphql_compose_image_style
  - graphql_compose_menus
  - graphql_compose_metatags
  - graphql_compose_routes
  - graphql_compose_users
  - graphql_compose_views
  - help
  - metatag
  - metatag_open_graph
  - metatag_twitter_cards
  - pathauto
  - views_ui
  - view_unpublished
  - webform
  - webform_rest
  - weight

config:
  strict: false
  import:
    ckeditor_media_embed: '*'
    metatag:
      - metatag.metatag_defaults.global
    coffee: '*'
    gin:
      - gin.settings
      - block.block.gin_breadcrumbs
      - block.block.gin_content
      - block.block.gin_help
      - block.block.gin_local_actions
      - block.block.gin_messages
      - block.block.gin_page_title
      - block.block.gin_primary_local_tasks
    gin_login: '*'
    node:
      - views.view.content
      - views.view.content_recent
      - views.view.frontpage
  actions:
    system.site:
      simple_config_update:
        page.front: /admin
    system.theme:
      simple_config_update:
        admin: 'gin'
        default: 'gin'
    ckeditor_media_embed.settings:
      simpleConfigUpdate:
        embed_provider: '//noembed.com/embed?url={url}&callback={callback}'
